FROM daskdev/dask-notebook:2021.10.0-py3.8
RUN apt update && apt install curl git ssh cmake ack g++ vim tmux -yq
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/qooba/vim-python-ide/master/setup.sh)"

RUN git clone -b master https://github.com/qooba/feast.git
RUN cd feast && make install-python-ci-dependencies
#RUN cd feast/sdk/python && pip install -e .

RUN pip install dask-kubernetes --upgrade
RUN pip install dask-deltatable deltalake pyarrow fastparquet 
RUN pip install mlflow boto3 
RUN pip install jedi==0.17.2
RUN pip install dask-ml dask_xgboost 

RUN pip install notebook rise
RUN pip install json2html cookiecutter
#ENV PYTHONPATH="/app:${PYTHONPATH}"
#WORKDIR /app

#ENTRYPOINT /bin/bash
